apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: main-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: example.com/external-nfs
parameters:
  server: 10.0.0.50
  path: /mnt/DataDrive/nfs
  readOnly: "false"