---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl-certs
  labels:
    type: local
spec:
  storageClassName: nfs-main
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/"