---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "pihole"
  name: "pihole"
spec:
  storageClassName: "main-nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"
---