- name: Extend the logical volume to take all remaining space of the PVs and resize the underlying filesystem
  lvol:
    vg: "{{ linux_vg }}"
    lv: "{{ linux_lv }}"
    size: 100%PVS
    resizefs: true