- hosts: new-workers 
  become: yes
  tasks:

    - name: Disable swap for current session
      command: swapoff -a
      become: true

    - name: Disable swap permanently, persist reboots
      replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: yes

    - name: allow '{{ VAULT_ubuntu_user }}' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '{{ VAULT_ubuntu_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    
    - name: create Docker config directory
      file: path=/etc/docker state=directory

    - name: changing Docker to systemd driver
      copy:
       dest: "/etc/docker/daemon.json"
       content: |
         {
         "exec-opts": ["native.cgroupdriver=systemd"]
         }

    - name: install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes' APT repository
      apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: 'kubernetes'

    - name: install kubelet
      apt:
        name: kubelet=1.22.4-00
        state: present
        update_cache: true

    - name: install kubeadm
      apt:
        name: kubeadm=1.22.4-00
        state: present
       
    - name: install kubectl
      apt:
        name: kubectl=1.22.4-00
        state: present
        force: yes

    - name: Generate join token
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd
      delegate_to: "{{ groups['masters'][0] }}"
    
    - set_fact:
        kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
    
    - debug: var=kubeadm_join
    
    - name: Store join command
      action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"
    
    - name: Run kubeadm join
      shell: "{{ kubeadm_join }} --ignore-preflight-errors=swap"